UnrealMultiple/TShockPlugin

AutoTeam/AutoTeam.csproj, AutoTeam/AutoTeamPlus.cs, AutoTeam/Configuration.cs, Plugin.sln
=> 添加插件：AutoTeam(自动队伍)

AutoBroadcast/AutoBroadcast.cs
[fix autob 防止协议端空引用卡服](https://github.com/Controllerdestiny/TShockPlugin/commit/46abe984d95a7731a03390c38954eece7bcce9ef)
=> fix autob 防止协议端空引用卡服

ItemPreserver/Configuration.cs, ItemPreserver/ItemPreserver.cs
fix ItemPreserver 在使用 ply 作为字典键之前，先检查其是否为 null
=> fix ItemPreserver 在使用 ply 作为字典键之前，先检查其是否为 null

journeyUnlock/journeyUnlock.cs
fix 给/i解锁 加了个AllowServer = false
=> fix 给/i解锁 加了个AllowServer = false

Platform/Main.cs, Platform/Platform.csproj, Platform/README.md, Plugin.sln, README.md
=> add Platform 判断玩家设备

README.md
=> 文档：主文档修改错别字

BuildHelper.py
=> 工作流：将仓库主文档打包到插件包里

HelpPlus/README.md, README.md
=> 文档：为HelpPlus添加文档

AutoBroadcast/ABConfig.cs, AutoBroadcast/AutoBroadcast.cs
=> 修复: AutoBroadcast的编码问题

CaiLib/Text.cs
=> 更新：CaiLib添加生成渐变色的方法TSPlayer.SendGradientMessage(string msg)

CaiBot/MessageHandler.cs
=> 更新：CaiBot新增查背包功能

README.md
=> 文档：主页文档添加小标签

CaiBot/MessageHandler.cs, CaiBot/Utils.cs
=> 更新：CaiBot查背包增加Buff查询(适配永久Buff)

WikiLangPackLoader/WikiLangPackLoader.csproj
=> 修复：WikiLangPackLoader语言包编译时内嵌

.github/workflows/build.yml
=> 工作流：非master分支触发编译

ConsoleSql/Plugin.cs
=> 更新：ConsoleSql表格对齐

Platform/Main.cs
=> 修复：修复Platform报错

.github/workflows/plugins_publish.yml, Plugins.json
示例: 
https://gh.jasonzeng.dev/https://raw.githubusercontent.com/ACaiCat/TShockPlugin/master/Plugins.json
https://raw.githubusercontent.com/ACaiCat/TShockPlugin/master/Plugins.json
=> 工作流：自动生成Plugins.json用于通过API检查插件最新版本

HelpPlus/Help.cs
=> 更新：Help <命令> 中提示使用者使用/whynot查看详细权限

RandRespawn/MainPlugin.cs
=> 修复：RandReSpawn改为utf8

README.md
=> 文档：修复主页文档构建标签错误

Plugin.sln, README.md, TimerKeeper/DB.cs, TimerKeeper/MainPlugin.cs, TimerKeeper/README.md, TimerKeeper/TimerKeeper.csproj
=> 添加插件：TimerKeeper 保存计时器

CaiBot/Plugin.cs
=> 更新：CaiBot使用域名建立ws连接，方便跑路

.github/workflows/plugins_publish.yml, ForumHelper.py
[链接](https://tr.monika.love/resources/104/)
目前没发现啥大问题
=> 工作流：自动更新论坛主页MD

.github/workflows/plugins_publish.yml, ForumHelper.py, README.md
*文档：主页文档引导下载
*工作流：支持TRHUB和BBSTR
*工作流：忽略更新论坛报错
=> 工作流：支持TRHUB和BBSTR |  文档：主页文档引导下载

History/History.cs
更新：调整History优先级，防止玩家没成功放置方块也记录
=> 更新：调整History优先级，防止玩家没成功放置方块也记录

History/History.cs
[更新：history修改钩子注册优先级](https://github.com/Controllerdestiny/TShockPlugin/commit/161e1faff4c233a14f2bf02bdd3515e7c224f521)
=> 更新：history修改钩子注册优先级

ForumUpdate.py
修改了脚本自动更新 tr.monika.love 论坛的方式，现在脚本会通过论坛中资源帖的发布更新功能来同步仓库更新信息，效果更好。
=> 工作流: 修改了脚本自动更新 tr.monika.love 论坛的方式

Economics.NPC/Config.cs, Economics.NPC/Plugin.cs
=> 更新: Economics.NPC实现进度条件

Plugin.sln, README.md, SessionSentinel/README.md, SessionSentinel/SessionSentinel.cs, SessionSentinel/SessionSentinel.csproj
添加插件：SessionSentinel 处理长时间不发送数据包的玩家
=> 添加插件：SessionSentinel 处理长时间不发送数据包的玩家

Economics.Skill/AIStyle.cs, Economics.Skill/Skill.cs, Economics.Skill/Utils.cs, Economics.Task/Plugin.cs, EconomicsAPI/Utils/SpawnProjectile.cs
=> 修复: Economics.Skill ai样式误判

Plugin.sln, README.md, TeleportRequest/Config.cs, TeleportRequest/README.md, TeleportRequest/TPRequest.cs, TeleportRequest/TeleportRequest.cs, TeleportRequest/TeleportRequest.csproj
添加插件：传送请求TeleportRequest，还有东西要改，暂时先这样
=> 添加插件：传送请求TeleportRequest

HelpPlus/Conifg.cs, HelpPlus/Help.cs, HelpPlus/HelpPlus.csproj, HelpPlus/README.md
=> 更新: HelpPlus修复/death、/roll等原版命令

BuildHelper.py
=> 工作流：提高打包压缩等级，以减小插件包体积

ServerTools/Config.cs, ServerTools/Plugin.cs
限制发言长度
> [!NOTE]
> 没用的选项自行删掉哦~
=> 更新: ServerTool 添加发言长度限制

.github/workflows/plugins_publish.yml, .github/workflows/pull_request_check.yml, BuildHelper.py
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> 工作流: 干掉PDF转换

ForumHelper.py, ForumUpdate.py
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> 工作流: 干掉bbstr同步

CaiBot/Plugin.cs, CaiLib/Plugin.cs
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> 更新: 解决CaiBot，CaiLib 加载内嵌资源冲突

ChestRestore/ChestRestore.csproj, ChestRestore/MainPlugin.cs, ChestRestore/README.md, Plugin.sln, README.md
=> 上传ChestRestore

Economics.WeaponPlus/WeaponPlusDB.cs
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> 修复: Economics.WeaponPlus 数据库可能存在注入的问题

.github/workflows/forum_update.yml, .github/workflows/plugins_publish.yml
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> 工作流: 自动更新子模块

.github/workflows/forum_update.yml, .github/workflows/plugins_publish.yml
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> 工作流: 尝试修复子模块更新

.github/workflows/forum_update.yml, .github/workflows/plugins_publish.yml
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> 工作流：再次尝试修复子模块更新

.github/workflows/forum_update.yml, .github/workflows/plugins_publish.yml
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> 工作流: 尝试修复子模块 X2

.github/workflows/forum_update.yml, .github/workflows/plugins_publish.yml
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> 工作流: 尝试修复子模块 X3

.github/workflows/forum_update.yml, .github/workflows/plugins_publish.yml
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> 工作流: 修复子模块 X4

.github/workflows/forum_update.yml, .github/workflows/plugins_publish.yml
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> 工作流: 修复子模块 X5

.github/workflows/plugins_publish.yml
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> 工作流: 尝试修复子模块 X6

.github/workflows/plugins_publish.yml
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> 工作流: 尝试更新子模块 X7

.github/workflows/plugins_publish.yml
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> 工作流: 修复子模块 X我也不知道多少了

.github/workflows/plugins_publish.yml
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> 工作流: 修复子模块 X我也不知道多少了  +1        

.github/workflows/plugins_publish.yml
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> 工作流: 修复子模块 最后一次.jpg

.github/workflows/update_submodules.yml
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> 工作流: 每日自动更新子模块

AutoPluginManager/Plugin.cs, Economics.WeaponPlus/WeaponPlusDB.cs, WeaponPlusCostCoin/WeaponPlus.cs
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> 修复: Economics.WeaponPlus数据库报错

InstallTShock.ps1
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> 更新: pwsh脚本自动检测并安装.net

.gitignore
=> chore: update .gitignore [skip ci]

.github/workflows/plugins_publish.yml, BuildHelper.py
=> 工作流：自动更新插件包到Gitee

.github/workflows/pull_request_check.yml
=> chore: update .github/pull_request_check.yml

BuildHelper.py
=> 工作流：修复Gitee插件包覆盖问题

BuildHelper.py
=> 工作流：修复打包脚本 X2

.github/workflows/build.yml, scripts/POFileUpdater.ps1, scripts/POFileUpdater.py, scripts/POFileUpdater.sh
=> scripts(POFileUpdater): test

.github/workflows/build.yml
=> workflows(build): run POFileUpdater without root privilege

.github/workflows/build.yml, src/AutoPluginManager/AutoPluginManager.csproj, src/Autoclear/Autoclear.csproj, src/VeinMiner/VeinMiner.csproj
=> fix(workflows): build.yml GetText.Extractor not found

.github/workflows/build.yml
=> fix(workflows): build.yml not triggering when push

.github/workflows/build.yml, scripts/ForumHelper.py, scripts/GiteeSync.py
=> fix(scripts): ForumHelper.py and GiteeSync.py minor fixes

src/AutoPluginManager/Plugin.cs, src/RandRespawn/MainPlugin.cs
=> 更新：autopluginmanager 下载插件自动加载

.github/workflows/build.yml
=> 工作流：最后一步发布插件包

.github/ISSUE_TEMPLATE/feature_request.yaml
=> 文档: 修正议题模板

README.md, README_en.md, scripts/ForumHelper.py
=> 工作流: 修复论坛子模块链接错误

scripts/i18n.ps1
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
移除无用代码
=> update : i18n.ps1 script

scripts/zi18n.ps1
=> feat(script/zi18n): new i18n script

.github/workflows/build.yml
=> fix(workflows/build): pot file updating

Plugin.sln, README.md, README_en.md, src/LazyAPI/Attributes.cs, src/LazyAPI/Commands/Attributes.cs, src/LazyAPI/Commands/Command.HelpCommand.cs, src/LazyAPI/Commands/Command.cs, src/LazyAPI/Commands/CommandBase.cs, src/LazyAPI/Commands/CommandHelper.cs, src/LazyAPI/Commands/CommandParser.cs, src/LazyAPI/Commands/SingleCommand.cs, src/LazyAPI/ConfigFiles/JsonConfigBase.cs, src/LazyAPI/ConfigFiles/JsonData/ItemData.cs, src/LazyAPI/Database/Db.cs, src/LazyAPI/Database/DisposableQuery.cs, src/LazyAPI/Database/PlayerRecordBase.cs, src/LazyAPI/Database/RecordBase.cs, src/LazyAPI/LazyAPI.csproj, src/LazyAPI/LazyPlugin.cs, src/LazyAPI/PluginContainer.cs, src/LazyAPI/README.md, src/LazyAPI/RestHelper.cs, src/LazyAPI/TimingUtils.cs, src/LazyAPI/Utils.cs, src/LazyAPI/i18n/template.pot, src/LazyAPI/i18n/zh-CN.po, template.targets
=> add: LazyAPI common library

src/ChestRestore/MainPlugin.cs, src/ChestRestore/README.md
=> fix：将失效包号ChestName改为ChestOpen

src/EconomicsAPI/Economics.cs, src/EconomicsAPI/Utils/Helper.cs
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> fix TSManager initiate error

.github/workflows/build.yml
=> Update dotnet version

.github/workflows/build.yml, src/CaiBot/manifest.json, src/DumpPluginsList/DumpPluginsList.cs
=> feat(apm): manifest.json for overriding entries in Plugin.json

scripts/zi18n.ps1
=> fix(scripts/zi18n): mo file not generated when no updates in pot file

src/LazyAPI/CircularQueue.cs, src/LazyAPI/ConfigFiles/JsonConfigBase.cs, src/LazyAPI/PluginContainer.cs
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> feat: LazyAPI CircularQueue

.github/workflows/build.yml, README.md, README_EN.md, README_ES.md
I am willing to help with support and translation into Spanish, I verify and approve that the translation is as correct as possible
Doc: Added README_ES.md
Doc: Update README_EN.md and README.md to support README_ES.md
=> README：Soporte español

src/CaiRewardChest/Plugin.cs, src/CaiRewardChest/RewardChest.cs, src/ServerTools/Plugin.cs, src/ServerTools/README.md
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
=> fix: ServerTool hook  and RewardChest db error

template.targets
=> Action: temporarily update to TShock5.2.1

src/PermaBuff/DB.cs, src/PermaBuff/Playerbuffs.cs, src/PermaBuff/Plugin.cs, src/PermaBuff/README.md
加入/cbuff all子命令
与其对应权限：clearbuffs.admin
> [!NOTE]
> 没用的选项自行删掉哦~
=> update PermaBuff v1.0.2 加入清理所有buff子命令

.github/workflows/build.yml
=> fix(action): 修复同步插件包时报错

template.targets
=> chore(*): 改用`TShock` Nuget包

src/ZHIPlayerManager/README.en-US.md
=> Docs: Add README.en-US.md

src/HouseRegion/Config.cs, src/HouseRegion/HouseRegion.csproj, src/HouseRegion/PacketReceive.cs, src/HouseRegion/Plugin.cs, src/HouseRegion/Utils.cs
=> fix: HouseRegion Click on the showcase for lost items

src/AutoPluginManager/Internal/CommandAdapter.cs, src/AutoPluginManager/Internal/PluginManagementContext.cs, src/AutoPluginManager/Internal/PluginVersionInfo.cs, src/AutoPluginManager/Plugin.cs, src/AutoPluginManager/Utils.cs, src/Dummy/manifest.json, src/DumpPluginsList/DumpPluginsList.cs, src/Economics.Skill/Command.cs, src/Economics.Skill/Skill.cs
=> update: Plugin Description Multi-language support

.github/workflows/build.yml, .github/workflows/crowdin.yml, crowdin.yml
=> workflows: crowdin ci

src/LazyAPI/README.en-US.md
=> Docs(LazyApi): Create README.en-US.md

.github/workflows/crowdin.yml
=> refactor(workflows/crowdin): push to i18n branch instead

src/ChattyBridge/Config.cs, src/ChattyBridge/Plugin.cs
=> fix: ChattyBridge ForwardMsg Error

src/Invincibility/README.en-US.md
=> Docs(Invicibility): Create README.en-US.md

src/ItemBox/README.en-US.md
=> Docs(ItemBox): Create README.en-US.md

src/History/README.en-US.md
=> Docs(History): Create README.en-US.md

src/ItemPreserver/README.en-US.md
=> Docs(ItemPreserver): Create README.en-US.md

src/RegionView/README.en-US.md
=> Docs(RegionView): Create README.en-US.md

src/PacketsStop/README.en-US.md
=> Docs(PacketStop): Create README.en-US.md

src/OnlineGiftPackage/README.en-US.md
=> Docs(Online Gift Package): Create README.en-US.md

src/DataSync/README.en-US.md
=> Docs(DataSync): Create README.en-US.md

src/CreateSpawn/README.en-US.md
=> Docs(CreateSpawn): Create README.en-US.md

src/CaiBot/Login.cs, src/CaiBot/Plugin.cs
=> [紧急] fix(CaiBot): fix login always use whitelist cache

src/ServerTools/Plugin.Commamd.cs, src/ServerTools/Plugin.cs, src/ServerTools/README.en-US.md, src/ServerTools/README.md
=> [ServerTools]: feat Execute commands for the specified player

src/Economics.Skill/Skill.cs, src/Economics.Skill/Utils.cs
=> [economic_skill] fix DynamicDamage The value is incorrect

src/CaiBot/CaiBotApi.cs
=> fix(CaiBotPlugin): 修复`上传地图`文件名错误

.config/dotnet-tools.json
Reverts UnrealMultiple/TShockPlugin#786
=> Revert "chore(deps): update dependency gettext.net.extractor to v8"

Plugin.sln, src/AutoTeam/Configuration.cs, src/EssentialsPlus/Config.cs, src/EssentialsPlus/Db/MuteManager.cs, src/EssentialsPlus/EssentialsPlus.cs, src/EssentialsPlus/EssentialsPlus.csproj, src/EssentialsPlus/PlayerInfo.cs, src/EssentialsPlus/README.md, src/TShockConfigMultiLang/Config.cs
=> 更新：EssentialsPlus的config使用lazyapi，禁言判断uuid，名字，ip

.github/workflows/build.yml
=> workflow(build): add workflow dispatch

src/RolesModifying/README.en-US.md, src/SmartRegions/Plugin.cs, src/SmartRegions/README.en-US.md, src/SmartRegions/README.md, src/SmartRegions/i18n/en-US.po
=> update:smartregion en

src/AutoPluginManager/Internal/CommandAdapter.cs, src/AutoPluginManager/Plugin.cs, src/AutoPluginManager/README.en-US.md, src/AutoPluginManager/README.md
=> [AutoPluginManager]: fix command apm il

src/CaiBot/CaiBotApi.cs, src/CaiBotLite/CaiBotApi.cs, src/CaiBotLite/Login.cs, src/CaiBotLite/Plugin.cs, src/CaiBotLite/README.md
=> fix(CaiBot):修复白名单登录时空引用报错

src/Platform/Main.cs, src/Platform/PlatformTool.cs, src/Platform/README.en-US.md, src/Platform/README.md
=>  feat(Platform):支持在聊天格式中显示设备

.config/readme-templates/README.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/report_bug.yaml
=> docs(README,issue-templates): 修改主页文档以及问题模板

src/Economics.Skill/JSInterpreter/JSFunctions.cs
=> [skill]: Add function Schedule

src/Economics.Skill/JSInterpreter/JSFunctions.cs, src/Economics.Skill/Skill.cs
=> [skill]: fix Schedule error and SendPackage function Parameters

src/ConsoleSql/README.en-US.md
=> Docs(ConsoleSql): Create README.en-US.md

src/CaiLib/README.en-US.md
=> Docs(CaiLib): Create README.en-US.md

src/CaiPacketDebug/README.en-US.md
=> Docs(CaiPacketDebug):Create README.en-US.md

src/ListPlugins/README.en-US.md
=> Docs(ListPlugins): Create README.en-US.md

Plugins.json, src/EconomicsAPI/DB/CurrencyManager.cs, src/EconomicsAPI/Economics.cs
=> fix 显示信息中货币数量显示并更新版号

src/Economics.Skill/JSInterpreter/Interpreter.cs, src/Economics.Skill/README.md, src/Economics.Skill/Skill.cs, src/Economics.Skill/Utils.cs
=> [skill]: 添加参数projectile index

src/ProgressRestrict/README.en-US.md
=> Doc(ProgressRestrict): Create README.en-US.md

src/JourneyUnlock/README.en-US.md
=> Docs(JourneyUnlock): Create README.en-US.md

src/MusicPlayer/README.en-US.md
=> Docs(MusicPlayer): Create README.en-US.md

src/NormalDropsBags/README.en-US.md
=> Docs(NormalDropsBag): Create README.en-US.md

src/RestInventory/README.en-US.md
=> Docs(RestInventroy): Create README.en-US.md

src/WikiLangPackLoader/README.en-US.md
=> Docs(WikiLangPackLoader): Create README.en-US.md

src/SpclPerm/README.en-US.md
=> Docs(SpclPerm): Create README.en-US.md

src/ShortCommand/README.en-US.md
=> Docs(ShortCommand): Create README.en-US.md

src/Economics.Skill/README.md
=> docs(Economics.Skill): 将js方法定义移入代码块中

src/SimultaneousUseFix/SimultaneousUseFix.cs, src/SimultaneousUseFix/SimultaneousUseFix.csproj, src/TransferPatch/ILTranslate.cs
=> fix: SimultaneousUseFix使用nuget引用

src/SwitchCommands/README.en-US.md
=> Docs(SwitchCommand): Create README.en-US.md

src/Sandstorm/README.en-US.md
=> Docs(SandStorm): Create README.en-US.md

src/Respawn/README.en-US.md
=> Docs(Respawn): Create README.en-US.md

src/GenerateMap/README.en-US.md
=> Docs(GenerateMap): Update README.en-US.md

src/Lagrange.XocMat.Adapter/README.en-US.md
=> Docs(Lagrange.XocMat.Adapter): Create README.en-US.md

src/StatusTextManager/README.en-US.md
=> Docs(StatusTextManager): Create README.en-US.md

src/SimultaneousUseFix/README.en-US.md
=> Docs(SimultaneousUseFix): Create README.en-US.md

src/RainbowChat/README.en-US.md
=> Docs(RainbowChat): Create README.en-US.md

src/ServerTools/Plugin.Online.cs, src/ZHIPlayerManager/README.md, src/ZHIPlayerManager/TSPlayerBanHelper.cs, src/ZHIPlayerManager/ZHIPM.Initialize.cs, src/ZHIPlayerManager/ZHIPM.cs
=> [zpm]: zban 命令添加时长

src/Economics.WeaponPlus/WeaponPlus.cs
=> [WeaponPlus]: 添加修改武器时的日志信息

src/QRCoder/README.en-US.md
=> Docs(QrCoder): Create README.en-US.md

src/SignInSign/README.en-US.md
=> Docs(SignInSign): Create README.en-US.md

src/WeaponPlus/README.en-US.md
=> Docs(WeaponPlusCostCoin): Create README.en-US.md

src/TransferPatch/README.en-US.md
=> Docs(TransfersPatch): Create README.en-US.md

src/UnseenInventory/README.en-US.md
=> Docs(Unseeninventory): Create README.en-US.md

src/ProxyProtocolSocket/README.en-US.md
=> Docs(ProxyProtocolSocket): Create README.en-US.md

src/ShowArmors/README.en-US.md
=> Docs(ShowArmors): Create README.en-US.md

src/RolesModifying/Plugin.cs, src/ServerTools/Plugin.Commamd.cs, src/ServerTools/Plugin.cs
=> fix: Command Use command in Console
