- Plugin.sln
- README.md
- RainbowChat/README.md
- RainbowChat/RainbowChat.cs
- RainbowChat/RainbowChat.csproj
> 添加插件：RainbowChat 彩虹聊天

- Plugin.sln
- README.md
- SwitchCommands/CommandInfo.cs
- SwitchCommands/Database.cs
- SwitchCommands/PluginCommands.cs
- SwitchCommands/README.md
- SwitchCommands/SwitchCommands.cs
- SwitchCommands/SwitchCommands.csproj
> 添加SwitchCommands

- EssentialsPlus/Commands.cs
- EssentialsPlus/Config.cs
- EssentialsPlus/Db/Home.cs
- EssentialsPlus/Db/HomeManager.cs
- EssentialsPlus/Db/MuteManager.cs
- EssentialsPlus/EssentialsPlus.cs
- EssentialsPlus/EssentialsPlus.csproj
- EssentialsPlus/Extensions/GroupExtensions.cs
- EssentialsPlus/Extensions/ITileExtensions.cs
- EssentialsPlus/Extensions/StringExtensions.cs
- EssentialsPlus/Extensions/TSPlayerExtensions.cs
- EssentialsPlus/Permissions.cs
- EssentialsPlus/PlayerInfo.cs
- EssentialsPlus/README.md
- Plugin.sln
- README.md
> Add EssentialsPlus

- PersonalPermission/DB.cs
- PersonalPermission/PPMain.cs
- PersonalPermission/PersonalPermission.csproj
- PersonalPermission/README.md
- Plugin.sln
- README.md
add 添加插件 PersonalPermission 玩家单独权限
> add 添加插件 PersonalPermission 玩家单独权限

- Plugin.sln
- README.md
- journeyUnlock/README.md
- journeyUnlock/journeyUnlock.cs
- journeyUnlock/journeyUnlock.csproj
> add 添加 journeyUnlock 解锁旅途物品

- PvPer/Commands.cs
- PvPer/Configuration.cs
- PvPer/PvPer.cs
> 更新 用UTF-8编码部分文件

- CriticalHit/Config.cs
- CriticalHit/CritMessage.cs
- CriticalHit/WeaponType.cs
- PvPer/DBManager/DPlayer.cs
- PvPer/DBManager/DbManager.cs
- PvPer/Tool/Pair.cs
- PvPer/Tool/Utils.cs
> 修复: 多个文件编码修复为utf-8

- ServerTools/Config.cs
- ServerTools/Plugin.cs
禁止快速放入箱子功能，目前没有能力禁止，因玩家在同时打开箱子与背包使用此功能，服务器不会收到85号包，且只有在这种情况下才能使用bug进行刷物品，其他情况禁止快速放入箱子功能毫无意义，故删除此功能。
> 修复: 修复ServerTools 禁止怪物捡钱无法生效得问题，移除禁止快速放入箱子功能

- Plugin.sln
- README.md
- Respawn/README.md
- Respawn/Respawn.cs
- Respawn/Respawn.csproj
- journeyUnlock/README.md
> 添加插件：Respawn 原地复活

- CaiBot/MessageHandler.cs
- CaiBot/Plugin.cs
> 更新：CaiBot获取世界名称

- ConsoleSql/ConsoleSql.csproj
- ConsoleSql/Plugin.cs
- ConsoleSql/README.md
- Plugin.sln
- README.md
> 添加插件：ConsoleSql(控制台SQL执行)

- AutoTeam/AutoTeamPlus.cs
- DeathDrop/DeathDrop.cs
修复：死亡掉落CommonRandomDrops为空时的空引用
删了点autoteam的无用代码
> 修复：死亡掉落CommonRandomDrops为空时的空引用

- .github/workflows/plugins_publish.yml
> 工作流：跳过Git PUSH报错，不显示下载和解压日志

- EconomicsAPI/Economics.cs
- EconomicsAPI/Utils/SpawnProjectile.cs
- ServerTools/Plugin.cs
> 更新: EconomicsAPI 尝试解决所谓的AI问题与持续时间

- Economics.Skill/Attributes/JavaScriptFunction.cs
- Economics.Skill/Economics.Skill.csproj
- Economics.Skill/JSInterpreter/Interpreter.cs
- Economics.Skill/JSInterpreter/JSFunctions.cs
- Economics.Skill/JSInterpreter/JsScript.cs
- Economics.Skill/JSInterpreter/PreprocessorDirectives.cs
- Economics.Skill/JSInterpreter/ScriptContainer.cs
- Economics.Skill/Model/SkillContext.cs
- Economics.Skill/Skill.cs
- Economics.Skill/Utils.cs
- EconomicsAPI/Extensions/Vector2Ext.cs
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
> 更新: Economics.Skill 添加执行js脚本

- InstallTShock.ps1
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
> 添加: pwsh 安装TShock脚本

- InstallTShock.ps1
- README.md
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
> 更新: win用户只需一行命令即可安装TShock

- .github/workflows/build.yml
- scripts/GiteeSync.py
> 工作流: 修复同步gitee插件包

- src/StatusTextManager/README.md
- src/StatusTextManager/SettingsModel/DynamicText.cs
- src/StatusTextManager/SettingsModel/IStatusTextSetting.cs
- src/StatusTextManager/StatusTextManager.cs
- src/StatusTextManager/Utils/Common.cs
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
> feat(StatusTextManager): DynamicText 动态文本内容

- src/LazyAPI/ConfigFiles/JsonConfigBase.cs
- src/LazyAPI/PluginContainer.cs
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
> update: LazyAPI Add File saving

- src/ServerTools/Config.cs
- src/ServerTools/DB/PlayerDeath.cs
- src/ServerTools/DB/PlayerOnline.cs
- src/ServerTools/Plugin.Commamd.cs
- src/ServerTools/Plugin.DeathRank.cs
- src/ServerTools/Plugin.Online.cs
- src/ServerTools/Plugin.cs
- src/ServerTools/ServerTools.csproj
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
> fix: ServerTools restApi request error

- .config/submodule-manifests/VBY.Common.json
- .config/submodule-manifests/VBY.GameContentModify.json
- .config/submodule-manifests/VBY.OtherCommand.json
- .config/submodule-manifests/VBY.PluginLoader.json
- .config/submodule_build.json
- .gitmodules
> Add(Common,OtherCommand,GameContentModify,PluginLoader): 添加部分常用VBY插件

- src/ServerTools/DB/PlayerDeath.cs
- src/ServerTools/DB/PlayerOnline.cs
- src/ServerTools/Plugin.cs
<-懒得写其实也没事->
> [!NOTE]
> 没用的选项自行删掉哦~
> fix: ServerTools Online DB Error

- .github/workflows/build.yml
> [工作流]: 下载临时文件时指定run id防止下载过去工作流中的文件
